version: '3.8'

services:
  # Development service with hot-reloading
  app-dev:
    image: node:20-alpine
    container_name: sundra-app-dev
    working_dir: /app
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - ./my.sundra.io.pem:/app/my.sundra.io.pem
      - ./my.sundra.io-key.pem:/app/my.sundra.io-key.pem
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "my.sundra.io:127.0.0.1"
    command: >
      sh -c "NODE_TLS_REJECT_UNAUTHORIZED=0 npm run dev -- --host 0.0.0.0"

  # Setup service for installing dependencies (run once)
  setup:
    image: node:20-alpine
    container_name: sundra-setup
    working_dir: /app
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    command: npm ci

volumes:
  node_modules:
